const types = {
  RECORD_USERINFO:'RECORD_USERINFO',
  CLEAR_USERINFO:'CLEAR_USERINFO',
  SET_SELECTED_MENU: 'SET_SELECTED_MENU',
  SET_SELECTED_NAME:'SET_SELECTED_NAME',
  SET_SELECTED_TYPE:'SET_SELECTED_TYPE',
  SET_OPENNAMES:'SET_OPENNAMES',
  SET_ACTIVENAME:'SET_ACTIVENAME',
  RECORD_SEARCH:'RECORD_SEARCH',
  RECORD_TAB:'RECORD_TAB',
  RECORD_INFOTEL:'RECORD_INFOTEL'
}
export default types;
